/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <iostream>

using namespace std;

int main() {
    int a{1}, b{2}, sum{0}; // initializing variables

    while ( a < 4000000 ){ // while loop that iterates as long as a is less than 4,000,000
        if ( a % 2 ==0 ){ // checking if the current number is an even number
            sum += a; // if it is even then add that number to the current number to get the total
        }

        int fib = a + b; //fib sequence calculations
        a = b;
        b = fib;
    }

    cout << sum; // output
}
